fix: unit tests when torch is installed
Backend unit tests were failing on my machine, where torch is installed.
This was caused by the fact that set_num_interop_threads was being
called twice. It was generating the following error:

	RuntimeError: cannot set number of interop threads after
	parallel work has started or set_num_interop_threads called

Tests were green in CI because torch is not installed there.

To address this issue, we propose the following changes:

1. Mock torch in all rag tests to ensure full consistency.
2. Don't try to set num_threads/num_interop_threads when unnecessary.

This addresses part of issue #369.